# =============================================================================
# OPEN CLAW — Powerlevel10k configuration  (RAINBOW · multi-line · left-aligned)
# =============================================================================
# Hand-tuned (not generated by `p10k configure`). Rainbow powerline style: each
# segment is a solid colored block separated by powerline arrows. Two lines —
# the colored ribbon on line 1, the ❯ prompt on line 2. The right prompt is
# intentionally empty so there is NO gap filler ("continuous spaces"/dots).
# Stowed to ~/.p10k.zsh by the `shell` module; sourced from ~/.zshrc step 8.
#
# NOTE: the prompt redraw / "auto carriage return" people see is NOT this file —
# it is the zsh-autocomplete plugin, disabled in ~/.zshrc. Needs a Nerd Font.
# =============================================================================

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob
  unset -m 'POWERLEVEL9K_*'

  # ── Layout: everything LEFT, two lines, right prompt empty (no gap fill) ────
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # platform glyph
    dir                     # current directory
    vcs                     # git status
    command_execution_time  # long-running command duration
    status                  # exit code (errors only)
    background_jobs         # backgrounded jobs
    direnv                  # direnv
    virtualenv pyenv        # python env (when active)
    nodenv node_version     # node env (project only)
    kubecontext             # k8s (on kubectl/helm only)
    terraform               # terraform workspace (on tf only)
    aws gcloud              # cloud (on relevant commands only)
    context                 # user@host (SSH / root only)
    newline                 # → line 2
    prompt_char             # ❯
  )
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()   # empty ⇒ no gap filler

  # ── Powerline ribbon style ─────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''   #
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='' #
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=

  # ── os_icon (grey block) ────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7

  # ── dir (blue block) ────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=15
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=60
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # ── vcs / git (green clean, yellow dirty) ───────────────────────────────────
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=0
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=3
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=0
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=2
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=0
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=1
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=232
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=8
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  # ── status / exec time / jobs / direnv ──────────────────────────────────────
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=1
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=232
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=2
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=0
  typeset -g POWERLEVEL9K_DIRENV_BACKGROUND=3
  typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=0

  # ── language / env (blue/green blocks) ──────────────────────────────────────
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=4
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=0
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_PYENV_BACKGROUND=4
  typeset -g POWERLEVEL9K_PYENV_FOREGROUND=0
  typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=2
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=0
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_NODENV_BACKGROUND=2
  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=0

  # ── kubecontext / terraform / cloud (purple/orange blocks, on-command) ──────
  typeset -g POWERLEVEL9K_KUBECONTEXT_BACKGROUND=5
  typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=255
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|k9s|kubectx'
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION='${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}'
  typeset -g POWERLEVEL9K_TERRAFORM_BACKGROUND=5
  typeset -g POWERLEVEL9K_TERRAFORM_FOREGROUND=255
  typeset -g POWERLEVEL9K_TERRAFORM_SHOW_DEFAULT=false
  typeset -g POWERLEVEL9K_AWS_BACKGROUND=208
  typeset -g POWERLEVEL9K_AWS_FOREGROUND=0
  typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_GCLOUD_BACKGROUND=4
  typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=255
  typeset -g POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gsutil|gcs|bq'

  # ── context (user@host — SSH / root only) ───────────────────────────────────
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=1
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=232
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=7
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=232
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  # Hide for the normal local user; show only for root / SSH.
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  # ── prompt_char (line 2 — transparent, green ok / red error) ────────────────
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=2
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=1
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIVIS,VIOWR}_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=

  # ── behavioral (the redraw / carriage-return killers) ───────────────────────
  # Instant prompt off (welcome TUI owns the terminal first), no transient prompt
  # (keeps every prompt the full multi-line frame), no hot reload.
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

  (( ! $+functions[p10k] )) || p10k reload
}

typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
