# =============================================================================
# OPEN CLAW — Powerlevel10k configuration
# =============================================================================
# Hand-tuned (not generated by `p10k configure`) so the prompt is correctly
# themed out of the box on macOS AND Linux. Stowed to ~/.p10k.zsh by the
# `shell` module; sourced from ~/.zshrc step 8.
#
# Palette: GitHub macOS Dark (truecolor hex) to match fastfetch / colorls /
# tmux / starship. Icons assume a Nerd Font terminal (installed in bootstrap.sh
# Step 7). Instant prompt is intentionally NOT used — the Open Claw welcome TUI
# owns the terminal first (see ~/.zshrc step 3).
# =============================================================================

# Temporarily change options for clean sourcing, restore at the end.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all POWERLEVEL9K_* so a stale option from a prior config can't leak in.
  unset -m 'POWERLEVEL9K_*'

  # GitHub macOS Dark palette ------------------------------------------------
  local blue='#58a6ff' green='#3fb950' purple='#bc8cff' orange='#d29922'
  local red='#ff7b72' muted='#8b949e' text='#c9d1d9' bg='#161b22'

  # ── Prompt layout ─────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # platform glyph (auto: apple on macOS, distro on Linux)
    dir                     # current directory
    vcs                     # git status
    newline                 # second line
    prompt_char             # ❯ (green ok / red error)
  )
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # exit code of last command
    command_execution_time  # how long the last command ran
    background_jobs         # presence of backgrounded jobs
    direnv                  # direnv status
    virtualenv pyenv        # python env
    nodenv node_version     # node env
    kubecontext             # k8s context (shown on kubectl/helm — see .zshrc)
    terraform               # terraform workspace
    aws gcloud              # cloud context
    context                 # user@host (only over SSH / as root)
    time                    # clock
  )

  # ── Global style ────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate
  typeset -g POWERLEVEL9K_BACKGROUND=                       # transparent segments
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '

  # Two-line frame ----------------------------------------------------------
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{$muted}╭─%f"
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX="%F{$muted}├─%f"
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{$muted}╰─%f "
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

  # ── os_icon ──────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=$purple

  # ── prompt_char ────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$green
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$red
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIVIS,VIOWR}_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

  # ── dir ───────────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$muted
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=60
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # ── vcs (git) ──────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$green
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$orange
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=$red
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=$muted
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  # ── status ───────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$red
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=$red
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=$green
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=$red

  # ── command_execution_time ──────────────────────────────────────────────
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$orange
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  # ── background_jobs ────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$green
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false

  # ── direnv ─────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=$orange

  # ── language / env segments ──────────────────────────────────────────────
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=$green
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_PYENV_FOREGROUND=$green
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=$green
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=$green

  # ── kubecontext ────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|k9s|kubectx'
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION='${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}'

  # ── terraform ──────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_TERRAFORM_FOREGROUND=$purple
  typeset -g POWERLEVEL9K_TERRAFORM_SHOW_DEFAULT=false

  # ── aws / gcloud ──────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_AWS_FOREGROUND=$orange
  typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gsutil|gcs|bq'

  # ── context (user@host — only over SSH or as root) ────────────────────────
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$red
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=$orange
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$muted
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  # Hide context for the normal local user; show only for root / SSH sessions.
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  # ── time ───────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$muted
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # ── behavioral ────────────────────────────────────────────────────────────
  # Instant prompt is handled (disabled) in ~/.zshrc; keep p10k quiet about it.
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # Transient prompt + a leading blank line both fight the shell-integration that
  # VS Code / Cursor / JetBrains inject into their built-in terminals: the multi-
  # line prompt ends up redrawing and spamming blank lines on every Enter ("keeps
  # entering newlines"). In those editor terminals, drop the transient redraw and
  # the leading newline — the GitHub-dark colors and the ╭─╰─ frame are kept. Real
  # standalone terminals (iTerm, kitty, Ghostty, Terminal.app, …) keep both.
  if [[ "$TERM_PROGRAM" == "vscode" || "$TERM_PROGRAM" == "Cursor" \
        || -n "${VSCODE_INJECTION-}${VSCODE_PID-}" \
        || "$TERMINAL_EMULATOR" == "JetBrains-JediTerm" || "$TERM" == "dumb" ]]; then
    typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
    typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
  else
    typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
  fi

  (( ! $+functions[p10k] )) || p10k reload
}

typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
