#!/usr/bin/env bash
# clin.sh — Open Claw "clin plugin" engine.
#
# clin (reekta92/clin-rs) is a TUI note manager inspired by Obsidian. This is
# the non-interactive engine for the plugin that lives *inside* the Obsidian
# sub-profile: it installs clin, and renders clin's config.toml from the SAME
# two sources of truth the rest of Open Claw already uses —
#   • the active color theme   (scripts/utils/theme.sh → CLAW_C_*)
#   • the Obsidian vault + the per-profile folder routing (shell/obsidian.zsh)
# so clin inherits the active palette and opens the active profile's folder,
# exactly like the `on`/`os`/`ov` helpers.
#
# RUN it (bash scripts/utils/clin.sh ...):
#   clin.sh install                 cargo install clin-rs (idempotent)
#   clin.sh render <out> [v] [f]    write a full config.toml to <out>
#                                   (v=vault root, f=folder name; both optional)
#   clin.sh sync                    render the persistent ~/.config/clin/config.toml
#   clin.sh setup                   install + sync
#   clin.sh theme <clin-name-of>    map a claw slug → clin built-in theme id
#
# The persistent config is a MANAGED file: it carries the sentinel below on its
# first line. `sync` refuses to overwrite a config that lacks the sentinel (a
# hand-tuned one) unless CLAW_CLIN_MANAGED=force. Opt out entirely with
# CLAW_CLIN_MANAGED=0. POSIX-portable (sh), mirrors theme.sh.

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
CLIN_SENTINEL="managed by the Open Claw clin plugin"
CLIN_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/clin/config.toml"

# Pull the active palette into CLAW_C_* (no-op-safe if theme.sh is absent).
if [ -r "$DOTFILES_DIR/scripts/utils/theme.sh" ]; then
    # shellcheck disable=SC1091
    . "$DOTFILES_DIR/scripts/utils/theme.sh"
fi

# Map an Open Claw theme slug → a clin built-in theme identifier. clin parses
# these case-insensitively (src/config.rs). Slugs with no clin sibling fall back
# to "default" — the per-color [ui] overlay below still carries the real palette.
clin_theme_for() {
    case "${1:-$CLAW_THEME_SLUG}" in
        catppuccin-mocha)  printf 'catppuccin_mocha' ;;
        tokyo-night)       printf 'tokyo_night' ;;
        rose-pine)         printf 'rose_pine' ;;
        gruvbox-material)  printf 'gruvbox' ;;
        *)                 printf 'default' ;;
    esac
}

# Render a complete clin config.toml. Args: <out> [vault-root] [folder-name].
# storage_path/default_folder are emitted only when given, so the persistent
# sync (no folder) and the per-shell launch (scoped folder) share one renderer.
# Colors come from CLAW_C_* (active theme); the [ui] keys are clin's documented
# per-color overrides, so the base `theme` is just a coherent starting point.
clin_render() {
    _out="$1"; _vault="${2:-}"; _folder="${3:-}"
    [ -n "$_out" ] || { printf 'clin.sh render: missing <out>\n' >&2; return 1; }
    mkdir -p "$(dirname "$_out")" 2>/dev/null
    {
        printf '# %s — generated by `claw clin sync`. Do NOT edit by hand.\n' "$CLIN_SENTINEL"
        printf '# Colors track the active theme (config/themes/%s); the vault +\n' "${CLAW_THEME_SLUG:-refined-dark}"
        printf '# folder track the Obsidian profile routing. Re-render: claw clin sync\n'
        printf '# Opt out: export CLAW_CLIN_MANAGED=0  (this file is then left alone).\n\n'

        printf '[core]\n'
        [ -n "$_vault" ]  && printf 'storage_path = "%s"\n' "$_vault"
        [ -n "$_folder" ] && printf 'default_folder = "%s"\n' "$_folder"
        printf 'mouse_enabled = true\n'
        printf 'confirm_on_delete = true\n\n'

        printf '[ui]\n'
        printf 'theme = "%s"\n' "$(clin_theme_for)"
        printf 'background = "transparent"\n'
        printf 'accent = "#%s"\n'      "${CLAW_C_BLUE:-58a6ff}"
        printf 'heading = "#%s"\n'     "${CLAW_C_PURPLE:-bc8cff}"
        printf 'success = "#%s"\n'     "${CLAW_C_GREEN:-3fb950}"
        printf 'destructive = "#%s"\n' "${CLAW_C_RED:-ff7b72}"
        printf 'muted = "#%s"\n'       "${CLAW_C_MUTED:-8b949e}"
        printf 'text = "#%s"\n'        "${CLAW_C_FG:-c9d1d9}"
        printf 'border = "#%s"\n'      "${CLAW_C_DIVIDER:-30363d}"
        printf 'tag = "#%s"\n'         "${CLAW_C_CYAN:-39c5ff}"
        printf 'folder = "#%s"\n'      "${CLAW_C_AMBER:-e3b341}"
    } > "$_out" 2>/dev/null
}

# Render the persistent ~/.config/clin/config.toml from active claw state.
# Honors the opt-out and refuses to clobber an unmanaged (hand-tuned) config.
clin_sync() {
    case "${CLAW_CLIN_MANAGED:-1}" in
        0|off|no) return 0 ;;
    esac
    if [ -f "$CLIN_CONFIG" ] && ! grep -q "$CLIN_SENTINEL" "$CLIN_CONFIG" 2>/dev/null; then
        if [ "${CLAW_CLIN_MANAGED:-1}" != "force" ]; then
            printf '  clin: %s looks hand-edited — not overwriting.\n' "$CLIN_CONFIG" >&2
            printf '  clin: re-run with CLAW_CLIN_MANAGED=force to let claw manage it.\n' >&2
            return 0
        fi
    fi
    # Vault root only (no folder): bare `clin` opens the registered vault; the
    # per-shell `cl` wrapper passes a scoped folder via --config at launch.
    _vault="${OBSIDIAN_VAULT:-}"
    clin_render "$CLIN_CONFIG" "$_vault" ""
    printf '  clin: synced %s (theme %s)\n' "$CLIN_CONFIG" "${CLAW_THEME_SLUG:-refined-dark}"
}

clin_install() {
    if command -v clin >/dev/null 2>&1; then
        printf '  clin: already installed (%s)\n' "$(command -v clin)"
        return 0
    fi
    if ! command -v cargo >/dev/null 2>&1; then
        printf '  clin: cargo not found — install Rust first (rustup).\n' >&2
        return 1
    fi
    printf '  clin: cargo install clin-rs …\n'
    cargo install clin-rs
}

_cmd="${1:-sync}"; shift 2>/dev/null || true
case "$_cmd" in
    install)        clin_install ;;
    render)         clin_render "$@" ;;
    sync|theme)     clin_sync ;;
    setup)          clin_install && clin_sync ;;
    map)            clin_theme_for "$@" ;;
    *) printf 'usage: clin.sh {install | render <out> [vault] [folder] | sync | setup | map [slug]}\n' >&2; exit 1 ;;
esac
