#!/usr/bin/env bash
# scripts/utils/generate-docs.sh
# Auto-generate ALIASES.md from source code

source "$(dirname "${BASH_SOURCE[0]}")/logger.sh"

# Resolve dotfiles root dynamically rather than hardcoding ~/.dotfiles
DOTFILES_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOCS_FILE="$DOTFILES_HOME/docs/ALIASES.md"
ALIAS_FILES=(
    "$DOTFILES_HOME/shell/aliases.zsh"
    "$DOTFILES_HOME/shell/security.zsh"
)

mkdir -p "$(dirname "$DOCS_FILE")"

generate_md() {
    log_info "Generating $DOCS_FILE..."
    
    echo "# Available Aliases & Commands" > "$DOCS_FILE"
    echo "" >> "$DOCS_FILE"
    echo "> Auto-generated by scripts/utils/generate-docs.sh" >> "$DOCS_FILE"
    echo "" >> "$DOCS_FILE"
    echo "| Command | Definition | Description |" >> "$DOCS_FILE"
    echo "|---------|------------|-------------|"

    for file in "${ALIAS_FILES[@]}"; do
        if [[ -f "$file" ]]; then
            while IFS= read -r line; do
                if [[ "$line" =~ ^alias[[:space:]]+([^=]+)=[\'\"]?([^#]+)[\'\"]?[[:space:]]*#[[:space:]]*(.*)$ ]]; then
                    name="${BASH_REMATCH[1]}"
                    # Clean up definition: remove trailing spaces/quotes
                    def=$(echo "${BASH_REMATCH[2]}" | sed "s/['\"]*//g" | xargs)
                    # Escape pipes for markdown table
                    def="${def//|/\\|}"
                    desc="${BASH_REMATCH[3]}"
                    
                    if [[ -n "$desc" ]]; then
                        echo "| \`$name\` | \`$def\` | $desc |" >> "$DOCS_FILE"
                    fi
                fi
            done < "$file"
        fi
    done
    
    log_success "Documentation generated at $DOCS_FILE"
}

generate_architecture_map() {
    ARCH_FILE="$DOTFILES_HOME/docs/ARCHITECTURE.md"
    log_info "Generating Architecture Map at $ARCH_FILE..."
    
    mkdir -p "$(dirname "$ARCH_FILE")"

    echo "# Open Claw CLI Architecture" > "$ARCH_FILE"
    echo "" >> "$ARCH_FILE"
    echo "> Auto-generated by \`scripts/utils/generate-docs.sh\`" >> "$ARCH_FILE"
    echo "" >> "$ARCH_FILE"
    echo "\`\`\`mermaid" >> "$ARCH_FILE"
    echo "graph TD" >> "$ARCH_FILE"
    echo "    UI[Open Claw TUI Welcome Screen] --> P[Agentic / Specialized Profiles]" >> "$ARCH_FILE"
    echo "    UI --> C[Core Shell Configuration]" >> "$ARCH_FILE"
    echo "    UI --> TK[Interactive Toolkit Menu]" >> "$ARCH_FILE"
    echo "" >> "$ARCH_FILE"
    
    # 1. Dynamically read Profiles
    PROFILE_DIR="$DOTFILES_HOME/shell/profiles"
    if [[ -d "$PROFILE_DIR" ]]; then
        for profile in "$PROFILE_DIR"/*.zsh; do
            if [[ -f "$profile" ]]; then
                prof_name=$(basename "$profile" .zsh)
                echo "    P --> P_${prof_name}(${prof_name} Profile)" >> "$ARCH_FILE"
            fi
        done
    fi
    echo "" >> "$ARCH_FILE"

    # 2. Dynamically read Toolkit Categories
    TOOLKIT_FILE="$DOTFILES_HOME/scripts/utils/toolkit.sh"
    if [[ -f "$TOOLKIT_FILE" ]]; then
        grep -E 'echo "  \$\{c_cyan\}[0-9]+\.\$\{c_reset\}' "$TOOLKIT_FILE" | while read -r line; do
            # Remove bash escape sequences and syntax
            clean_line=$(echo "$line" | sed 's/echo "  ${c_cyan}//g' | sed 's/${c_reset}//g' | sed 's/"//g' | xargs)
            # Extracted: e.g. "1. Git & Dev Ops"
            cat_num=$(echo "$clean_line" | cut -d'.' -f1)
            cat_name=$(echo "$clean_line" | cut -d'.' -f2- | xargs)
            echo "    TK --> TK_${cat_num}[\"${cat_num}. ${cat_name}\"]" >> "$ARCH_FILE"
        done
    fi

    echo "\`\`\`" >> "$ARCH_FILE"
    log_success "Architecture map generated at $ARCH_FILE"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    generate_md
    generate_architecture_map
fi
