#!/usr/bin/env bash
# scripts/utils/generate-docs.sh
# Auto-generate ALIASES.md from source code

source "$(dirname "${BASH_SOURCE[0]}")/logger.sh"

DOTFILES_HOME="${HOME}/.dotfiles"
DOCS_FILE="$DOTFILES_HOME/docs/ALIASES.md"
ALIAS_FILES=(
    "$DOTFILES_HOME/shell/aliases.zsh"
    "$DOTFILES_HOME/shell/security.zsh"
)

mkdir -p "$(dirname "$DOCS_FILE")"

generate_md() {
    log_info "Generating $DOCS_FILE..."
    
    echo "# Available Aliases & Commands" > "$DOCS_FILE"
    echo "" >> "$DOCS_FILE"
    echo "> Auto-generated by scripts/utils/generate-docs.sh" >> "$DOCS_FILE"
    echo "" >> "$DOCS_FILE"
    echo "| Command | Definition | Description |" >> "$DOCS_FILE"
    echo "|---------|------------|-------------|"

    for file in "${ALIAS_FILES[@]}"; do
        if [[ -f "$file" ]]; then
            while IFS= read -r line; do
                if [[ "$line" =~ ^alias[[:space:]]+([^=]+)=[\'\"]?([^#]+)[\'\"]?[[:space:]]*#[[:space:]]*(.*)$ ]]; then
                    name="${BASH_REMATCH[1]}"
                    # Clean up definition: remove trailing spaces/quotes
                    def=$(echo "${BASH_REMATCH[2]}" | sed "s/['\"]*//g" | xargs)
                    # Escape pipes for markdown table
                    def="${def//|/\\|}"
                    desc="${BASH_REMATCH[3]}"
                    
                    if [[ -n "$desc" ]]; then
                        echo "| \`$name\` | \`$def\` | $desc |" >> "$DOCS_FILE"
                    fi
                fi
            done < "$file"
        fi
    done
    
    log_success "Documentation generated at $DOCS_FILE"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    generate_md
fi
